# Generated by Django 5.2.4 on 2025-07-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]
